version: 1

disable_existing_loggers: False

# 日志输出格式
formatters:
  simple:
    format: "%(asctime)s [%(name)s] [%(levelname)s] %(filename)s %(funcName)s  %(lineno)d : %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'

# 日志配置
handlers:
  console:
    class: logging.StreamHandler # only console
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: base-tornado-infos.log
    maxBytes:  10485760 # 10MB
    backupCount: 5 # backupCount The number of backup files, if it exceeds this number, it will be automatically deleted
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: base-tornado-errors.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  fileLogger:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    #handlers: [info_file_handler, error_file_handler]
    propagate: no

# default logger
root:
  level: INFO
  handlers: [console, info_file_handler]